export const Valorant_agents = [
  {
    value: 1,
    src: "https://i.ibb.co/FH0K3j8/valorant-sage.png",
    alt: "valorant-Sage",
    label: "Sage",
    role: "Sentinel",
    discription: "",
    redirect: "/",
    details: "Barrier Orb, Slow Orb , Healing Orb , Resurrection",
    abilities: {
      First: {
        value: 1,
        quantity: 1,
        type: "First",
        power: "Wall",
        icon: "",
        discription: "Sage Wall Stops the enemies pushes",
      },
      Second: {
        value: 1,
        quantity: 1,
        type: "Second",
        power: "slow orbs",
        icon: "",
        discription: "Sage Wall is the best Wall",
      },
      Main: {
        value: 1,
        quantity: 1,
        type: "main",
        power: "Heal",
        icon: "",
        discription: "Sage Wall is the best Wall",
      },
      Ultimate: {
        value: 1,
        quantity: 1,
        type: "Ultimate",
        power: "Revive",
        icon: "",
        discription: "Sage Wall is the best Wall",
      },
    },
  },
  {
    value: 2,
    src: "https://i.ibb.co/v4nD0g4/valorant-jett.png",
    alt: "valorant-Jett",
    label: "Jett",
    role: "Duelist",
    discription: "",
    redirect: "/",
    details: "Cloudburst,Updraft, Tailwind , Blade Storm",
  },
  {
    value: 3,
    src: "https://i.ibb.co/LdTYnC3/valorant-skye.png",
    alt: "valorant-Skye",
    label: "Skye",
    role: "Initiator",
    discription: "",
    redirect: "/",
    details: "TRAILBLAZER, REGROWTH, GUIDING LIGHT , SEEKERS",
  },
  {
    value: 4,
    src: "https://i.ibb.co/2FpPJqq/valorant-reyna.png",
    alt: "valorant-Reyna",
    label: "Reyna",
    role: "Duelist",
    discription: "",
    redirect: "/",
    details: "DEVOUR, DISMISS, LEER , EMPRESS",
  },
  {
    value: 5,
    src: "https://i.ibb.co/VBtV8jD/valorant-fade.png",
    alt: "valorant-Fade",
    label: "Fade",
    role: "Initiators",
    discription: "",
    redirect: "/",
    details: "Seize, Prowler, Haunt , Nightfall",
  },
  {
    value: 6,
    src: "https://i.ibb.co/p18z6w5/valorant-yoru.png",
    alt: "valorant-Yoru",
    label: "Yoru",
    role: "Duelist",
    discription: "",
    redirect: "/",
    details: "FAKEOUT,BLINDSIDE, GATECRASH,  DIMENSIONAL DRIFT",
  },
  {
    value: 7,
    src: "https://i.ibb.co/cTdL6rL/valorant-brim.png",
    alt: "valorant-Brim",
    label: "Brimstone",
    role: "Controller",
    discription: "",
    redirect: "/",
    details: "STIM BEACON, INCENDIARY, SKY SMOKE,ORBITAL STRIKE",
  },
  {
    value: 8,
    src: "https://i.ibb.co/cTdL6rL/valorant-brim.png",
    alt: "valorant-noob",
    label: "Buddy",
    role: "God",
    discription: "",
    redirect: "/",
    details: "noob gaming skills, dell multi media keyboard, regear gaming mouse",
  },
];
